# Generated by Django 5.2.5 on 2025-08-20 03:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('required_count', models.IntegerField(default=10)),
                ('success_window_started_at', models.DateTimeField(blank=True, null=True)),
                ('success_window_seconds', models.IntegerField(default=5)),
            ],
        ),
    ]
