# Generated by Django 5.2.5 on 2025-08-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('crew_id', models.AutoField(primary_key=True, serialize=False)),
                ('crewname', models.CharField(max_length=100)),
                ('invitecode', models.CharField(default='002632fb', max_length=20, unique=True)),
                ('type', models.CharField(choices=[('running', '러닝'), ('hiking', '등산'), ('riding', '라이딩')], max_length=10)),
                ('member_count', models.PositiveIntegerField(default=1)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='crew_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
