# Generated by Django 5.2.5 on 2025-08-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crew',
            old_name='leader_id',
            new_name='leader',
        ),
        migrations.AlterField(
            model_name='crew',
            name='invitecode',
            field=models.CharField(default='66472f70', max_length=20, unique=True),
        ),
    ]
