# Generated by Django 5.2.5 on 2025-08-11 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_alter_crew_invitecode_alter_crew_leader_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='invitecode',
            field=models.CharField(default='0ec9f9f3', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='leader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_crews', to=settings.AUTH_USER_MODEL),
        ),
    ]
