# Generated by Django 5.2.5 on 2025-08-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='invitecode',
            field=models.CharField(default='cd5332dd', max_length=20, unique=True),
        ),
    ]
