# Generated by Django 5.2.5 on 2025-08-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0003_rename_leader_id_crew_leader_alter_crew_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='invitecode',
            field=models.CharField(default='bb886257', max_length=20, unique=True),
        ),
    ]
