# Generated by Django 5.2.5 on 2025-08-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0003_alter_crew_invitecode_alter_crew_leader_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='invitecode',
            field=models.CharField(default='780db9ec', max_length=20, unique=True),
        ),
    ]
