# Generated by Django 5.2.5 on 2025-08-14 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0003_alter_crew_invitecode'),
        ('crew', '0004_alter_crew_invitecode'),
    ]

    operations = [
    ]
