# Generated by Django 5.2.5 on 2025-08-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0005_alter_crew_invitecode_crewmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='invitecode',
            field=models.CharField(default='f1ff0188', max_length=20, unique=True),
        ),
    ]
