# Generated by Django 5.2.5 on 2025-08-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0005_merge_20250814_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='invitecode',
            field=models.CharField(default='2c32c7e5', max_length=20, unique=True),
        ),
    ]
