# Generated by Django 5.2.5 on 2025-08-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0006_alter_crew_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='invitecode',
            field=models.CharField(default='b906b9a4', max_length=20, unique=True),
        ),
    ]
