# Generated by Django 5.2.5 on 2025-08-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0010_alter_crew_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='invitecode',
            field=models.CharField(default='434f9e2b', max_length=20, unique=True),
        ),
    ]
