# Generated by Django 5.2.5 on 2025-08-20 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('crew_type', models.CharField(choices=[('running', '러닝'), ('hiking', '등산'), ('riding', '라이딩')], max_length=10)),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('target_distance', models.FloatField()),
                ('route_path', models.JSONField(default=list)),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.crewmember')),
            ],
        ),
    ]
